itapps/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name = 'register'),
    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('', include('itreporting.urls')),
]

itreporting/urls.py
from django.urls import path
from . import views

app_name = 'itreporting'
urlpatterns = [

    path('', views.home, name = 'home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label = 'Email address', help_text = 'Your SHU email address.')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

itreporting/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'itreporting/home.html', {'title': 'Welcome'})

def about(request):
    return render(request, 'itreporting/about.html', {'title': 'About'})

def contact(request):
    return render(request, 'itreporting/contact.html', {'title': 'Contact'})
# Create your views here.

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import UserRegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_staff = True  # Set the user as staff
            user.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! Now you can login!')
            return redirect('login')

        else:
            messages.warning(request, 'Unable to create account!')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form, 'title': 'Student Registration'})

itreporting/templates/itreporting/about.html
{% extends "itreporting/base.html" %}

{% block content %}

	<h1>About Student IT Services</h1>

{% endblock content %}

itreporting/templates/itreporting/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <title>Student IT Services - {{title}}</title>
<link rel="stylesheet" href="{% url 'itreporting:home' %}"/></head>

<body>
    <div class="container">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                <a class="navbar-brand mr-4" href="#">Student IT Services</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'itreporting:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'itreporting:about' %}">About</a>
                        <a class="nav-item nav-link" href="#">Report</a>
                        <a class="nav-item nav-link" href="{% url 'itreporting:contact' %}">Contact</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                         <!-- <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a> -->
                         <!-- <a form method="post" class="nav-item nav-link" action="{% url 'logout' %}" href="{% url 'logout' %}">Logout</a> -->
                           <!-- {% csrf_token %} 
                        </form> -->
                        <form id="frm_logout" method="post" action="{% url 'logout' %}"> {% csrf_token %} <a href="javascript:$('#frm_logout').submit();" class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700">Logout</a></form>
                            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                        </form>
                         {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                       <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                       </div>
                </div>
                </div>
            </nav>
        </header>
        <div class="row">
            <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>General Information</h3>
                    <p class='text-muted'>Lorem ipsum dolor sit amet, iudico docendi inciderint per eu, ea vis scripta senserit periculis.
                      <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Issues Reported</li>
                        <li class="list-group-item list-group-item-light">IT Policies</li>
                        <li class="list-group-item list-group-item-light">IT Regulations</li>
                        <li class="list-group-item list-group-item-light">Upcoming Events</li>
                      </ul>
                    </p>
                  </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

itreporting/templates/itreporting/contact.html
{% extends "itreporting/base.html" %}

{% block content %}

<body>

	<h1>Contact Student IT Services</h1>

{% endblock content %}

itreporting/templates/itreporting/home.html
{% extends "itreporting/base.html" %}

{% block content %}

<body>

	<h1>Welcome to Student IT Services</h1>

{% endblock content %}

users/templates/users/login.html
{% extends "itreporting/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Student IT Services - Login</legend>
            {{ form.as_p }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            You need to create an account?<a class="ml-2" href="{% url 'register' %}">Register</a>
        </small>
    </div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends "itreporting/base.html" %}

{% block content %}

    <h2>You have now been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted"><a class="ml-2" href="{% url 'login' %}">Login</a></small>
    </div>

{% endblock content %}

users/templates/users/register.html
{% extends "itreporting/base.html" %}
{% block content %}

<div class="content-section">
    <form method="POST">
        {% csrf_token %}
    
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Student Registration Form</legend>

        {{ form.as_p }}

    </fieldset>
    
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Register</button>
    </div>
    </form>

    <div class="border-top pt-3">
        <small class="text-muted">Are You Already Registered?<a class="ml-2" href="#">Login</a></small>
    </div>
</div>
{% endblock content %}